areacode: 330000
url: http://10.33.16.95:8088/gwssi-stats
src: src
finishout: upload
username: 10010001
password: 123456
driver: oci8 
dburl: zjbm/llx133@10.33.31.205:1521/orcl
table: 
  - {name: ent_info, 
     fieldsize: [2,32,18,1,9,50,100,4,1,3,1,2,1,6,15,20,20,20,6,200,6,60,200,3000,24,3,24,1,14,40,20,1,32,100,100,50,6,6,20,3,1,1,1,1,14,14] , 
     id: pripid ,
     result: audit_result,
     status: audit_status,
     shadowtable: ent_shadow,
     maxrows: 50000,
     details: 
         [ {name: 法人信息表,
           sizes: [2,32,32,100,2,60,60,60,100],                
           preid: pripid 
           },
           {name: 财务负责人,
           sizes: [2,32,32,50,2,60,30,30,100],                
           preid: pripid 
           },
           {name: 上级主管部门信息表,
           sizes: [2,32,32,18,9,100,50],                
           preid: pripid 
           },
           {name:  投资人信息,
           sizes: [2,32,32,10,200,2,60,10,60,14,20,100,10,30,10],                
           preid: pripid 
           },
           {name:  下级子公司信息表,
           sizes: [2,32,32,18,50,100,4,20,30,200,3000,20,20,6,20],                
           preid: pripid 
           },
           {name: 变更信息表,
           sizes: [2,32,32,100,4000,4000,20,20],                
           preid: pripid 
           },
           {name: 注销信息,
           sizes: [2,32,32,20,200 ],                
           preid: pripid 
           }]
     }
  
  - {name: abnormal_info, fieldsize: [2,32,18,100,50,20,2,6,6,32,6,14,14,3, 1,1,1,14,14] , 
     id: busexclist,
     result: abnormal_auditresult,
     status: abnormal_auditstatus,
     shadowtable: abnormal_shadow,
     maxrows: 100000,
     details: [] }
  - {name: illegal_info,fieldsize: [2,32,18,100,50,20,2,6,6,32,6,14,14,3, 1,1,1,14,14] , 
     id: illid,
     result: illegal_auditresult,
     status: illegal_auditstatus,
     shadowtable: illegal_shadow,
     maxrows: 200000,
     details: [] }
  - {name: annualreport_info, fieldsize: [2,32,15,18,100,8,4,30,100,6,100,1,6,4,1,9,24,24,24,24,24,24,24,24,2000,10,1,18,9,30,30,1,1,1,32,6,14,14,3,1,1,16,8,8,8,8,8,14,1] , 
     id: ancheid,
     result: annualreport_auditresult,
     status: annualreport_auditstatus,
     shadowtable: annualreport_shadow,
     maxrows: 2000,
     details:
          [{name: 企业认缴出资信息,
           sizes: [2,32,32,100,24,8,100,3],                
           preid: ancheid 
           },
           {name: 企业实缴出资信息,
           sizes: [2,32,32,100,24,8,100,3],                
           preid: ancheid 
           },
           {name: 企业对外投资信息,
           sizes: [2,32,32,1,100,200],                
           preid: ancheid
           },
           {name: 网站或网店信息,
           sizes: [2,32,32,1,1,100,100],                
           preid: ancheid 
           },
           {name: 股权变更信息,
           sizes: [2,32,32,2000,100,5,5,8],                
           preid: ancheid
           },] }
 
